// Morse code mappings per language, using each language's recognised
// international convention. Sources: ITU-R M.1677 (International Morse),
// Wikipedia "Morse code for non-Latin alphabets" and the JARL/ARRL Wabun chart.
//
// Each language declares the alphabet/morse it uses plus small native word,
// sentence and tongue-twister corpora used by the content generator.

export interface LanguageDef {
  id: string;
  label: string;
  /** Map of canonical character -> morse string. Latin/Cyrillic/Greek use
   *  upper-case keys; scripts without case use the natural form. */
  morse: Record<string, string>;
  /** Characters used for the "letters" content mode (lowercase if cased). */
  letters: string[];
  /** Native words used for "words" mode and as a fallback for sentences. */
  words: string[];
  /** Optional curated sentences (native). */
  sentences?: string[];
  /** Optional tongue-twisters (native). */
  twisters?: string[];
  /** Optional override of digits for "numbers" mode (defaults to 0-9). */
  numbers?: string[];
  /** RTL flag for display. */
  rtl?: boolean;
}

// Common punctuation/numerals shared by Latin- and Cyrillic-script languages.
const LATIN_PUNCT: Record<string, string> = {
  ".": ".-.-.-",
  ",": "--..--",
  "?": "..--..",
  "'": ".----.",
  "!": "-.-.--",
  "/": "-..-.",
  "(": "-.--.",
  ")": "-.--.-",
  "&": ".-...",
  ":": "---...",
  ";": "-.-.-.",
  "=": "-...-",
  "+": ".-.-.",
  "-": "-....-",
  _: "..--.-",
  '"': ".-..-.",
  "@": ".--.-.",
};

const DIGITS: Record<string, string> = {
  "0": "-----",
  "1": ".----",
  "2": "..---",
  "3": "...--",
  "4": "....-",
  "5": ".....",
  "6": "-....",
  "7": "--...",
  "8": "---..",
  "9": "----.",
};

const LATIN_CORE: Record<string, string> = {
  A: ".-",
  B: "-...",
  C: "-.-.",
  D: "-..",
  E: ".",
  F: "..-.",
  G: "--.",
  H: "....",
  I: "..",
  J: ".---",
  K: "-.-",
  L: ".-..",
  M: "--",
  N: "-.",
  O: "---",
  P: ".--.",
  Q: "--.-",
  R: ".-.",
  S: "...",
  T: "-",
  U: "..-",
  V: "...-",
  W: ".--",
  X: "-..-",
  Y: "-.--",
  Z: "--..",
};

// -------- English (International Morse, ITU-R M.1677) --------
const ENGLISH: LanguageDef = {
  id: "english",
  label: "english",
  morse: { ...LATIN_CORE, ...DIGITS, ...LATIN_PUNCT },
  letters: "abcdefghijklmnopqrstuvwxyz".split(""),
  words: [
    "the",
    "of",
    "and",
    "to",
    "in",
    "is",
    "you",
    "that",
    "it",
    "he",
    "was",
    "for",
    "on",
    "are",
    "as",
    "with",
    "his",
    "they",
    "at",
    "be",
    "this",
    "have",
    "from",
    "or",
    "one",
    "had",
    "by",
    "word",
    "but",
    "not",
    "what",
    "all",
    "were",
    "we",
    "when",
    "your",
    "can",
    "said",
    "there",
    "use",
    "an",
    "each",
    "which",
    "she",
    "do",
    "how",
    "their",
    "if",
    "will",
    "up",
    "other",
    "about",
    "out",
    "many",
    "then",
    "them",
    "these",
    "so",
    "some",
    "her",
    "would",
    "make",
    "like",
    "him",
    "into",
    "time",
    "has",
    "look",
    "two",
    "more",
    "write",
    "go",
    "see",
    "number",
    "no",
    "way",
    "could",
    "people",
    "my",
    "than",
    "first",
    "water",
    "been",
    "call",
    "who",
    "its",
    "now",
    "find",
    "long",
    "down",
    "day",
    "did",
    "get",
    "come",
    "made",
    "may",
    "part",
  ],
  sentences: [
    "the quick brown fox jumps over the lazy dog",
    "all that glitters is not gold",
    "a journey of a thousand miles begins with a single step",
    "the only way to do great work is to love what you do",
    "what we think we become",
    "the best time to plant a tree was twenty years ago",
    "in the middle of difficulty lies opportunity",
    "stay hungry stay foolish",
    "imagination is more important than knowledge",
  ],
  twisters: [
    "she sells seashells by the seashore",
    "peter piper picked a peck of pickled peppers",
    "how much wood would a woodchuck chuck",
    "red lorry yellow lorry red lorry yellow lorry",
    "fuzzy wuzzy was a bear fuzzy wuzzy had no hair",
    "betty bought a bit of bitter butter",
    "a proper copper coffee pot",
  ],
};

// -------- Spanish --------
const SPANISH: LanguageDef = {
  id: "spanish",
  label: "spanish",
  morse: {
    ...LATIN_CORE,
    ...DIGITS,
    ...LATIN_PUNCT,
    Ñ: "--.--",
    Á: ".--.-",
    É: "..-..",
    Í: "..",
    Ó: "---.",
    Ú: "..--",
  },
  letters: "abcdefghijklmnñopqrstuvwxyz".split(""),
  words: [
    "el",
    "la",
    "de",
    "que",
    "y",
    "a",
    "en",
    "un",
    "ser",
    "se",
    "no",
    "haber",
    "por",
    "con",
    "su",
    "para",
    "como",
    "estar",
    "tener",
    "le",
    "lo",
    "todo",
    "pero",
    "más",
    "hacer",
    "o",
    "poder",
    "decir",
    "este",
    "ir",
    "otro",
    "ese",
    "si",
    "me",
    "ya",
    "ver",
    "porque",
    "dar",
    "cuando",
    "muy",
    "sin",
    "vez",
    "mucho",
    "saber",
    "qué",
    "sobre",
    "mi",
    "alguno",
    "mismo",
    "yo",
    "también",
    "hasta",
    "año",
    "dos",
    "querer",
  ],
  sentences: [
    "el veloz murciélago hindú comía feliz cardillo y kiwi",
    "más vale tarde que nunca",
    "no por mucho madrugar amanece más temprano",
    "el saber no ocupa lugar",
  ],
  twisters: [
    "tres tristes tigres tragaban trigo en un trigal",
    "el cielo está enladrillado quién lo desenladrillará",
    "pepe pecas pica papas con un pico",
  ],
};

// -------- French --------
const FRENCH: LanguageDef = {
  id: "french",
  label: "french",
  morse: {
    ...LATIN_CORE,
    ...DIGITS,
    ...LATIN_PUNCT,
    À: ".--.-",
    Â: ".-.-",
    Ç: "-.-..",
    É: "..-..",
    È: ".-..-",
    Ê: "-..-.",
    Ë: "..-..",
    Î: "..",
    Ï: "..",
    Ô: "---.",
    Ù: "..--",
    Û: "..--",
    Ü: "..--",
  },
  letters: "abcdefghijklmnopqrstuvwxyzéèà".split(""),
  words: [
    "le",
    "la",
    "les",
    "de",
    "un",
    "une",
    "et",
    "être",
    "avoir",
    "que",
    "pour",
    "dans",
    "ce",
    "il",
    "qui",
    "ne",
    "sur",
    "se",
    "pas",
    "plus",
    "par",
    "grand",
    "mais",
    "comme",
    "ou",
    "si",
    "leur",
    "y",
    "dire",
    "elle",
    "avant",
    "deux",
    "même",
    "prendre",
    "aussi",
    "celui",
    "donner",
    "bien",
    "où",
    "fois",
    "vous",
    "encore",
    "nouveau",
    "aller",
    "cela",
    "entre",
    "premier",
    "vouloir",
    "déjà",
    "grand",
    "mon",
    "me",
  ],
  sentences: [
    "portez ce vieux whisky au juge blond qui fume",
    "petit à petit l oiseau fait son nid",
    "qui vivra verra",
    "à cœur vaillant rien d impossible",
  ],
  twisters: [
    "les chaussettes de l archiduchesse sont elles sèches",
    "un chasseur sachant chasser doit savoir chasser sans son chien",
    "ces six saucissons secs sont salés",
  ],
};

// -------- German --------
const GERMAN: LanguageDef = {
  id: "german",
  label: "german",
  morse: {
    ...LATIN_CORE,
    ...DIGITS,
    ...LATIN_PUNCT,
    Ä: ".-.-",
    Ö: "---.",
    Ü: "..--",
    ß: "...--..",
    CH: "----",
  },
  letters: "abcdefghijklmnopqrstuvwxyzäöüß".split(""),
  words: [
    "der",
    "die",
    "das",
    "und",
    "ich",
    "ist",
    "nicht",
    "sie",
    "es",
    "ein",
    "du",
    "mit",
    "zu",
    "auf",
    "für",
    "von",
    "im",
    "den",
    "aber",
    "dem",
    "wir",
    "auch",
    "an",
    "als",
    "so",
    "sich",
    "oder",
    "habe",
    "aus",
    "war",
    "mein",
    "wie",
    "wenn",
    "nur",
    "noch",
    "über",
    "kann",
    "nach",
    "bei",
    "schon",
    "jetzt",
    "mehr",
    "sehr",
    "ihr",
    "durch",
    "ja",
    "sein",
    "alle",
    "etwas",
    "wieder",
    "muss",
    "viel",
    "gut",
    "weiß",
    "keine",
    "macht",
  ],
  sentences: [
    "victor jagt zwölf boxkämpfer quer über den großen sylter deich",
    "übung macht den meister",
    "wer rastet der rostet",
    "morgenstund hat gold im mund",
  ],
  twisters: [
    "fischers fritz fischt frische fische frische fische fischt fischers fritz",
    "blaukraut bleibt blaukraut und brautkleid bleibt brautkleid",
    "der whiskeymixer mixt frischen whiskey",
  ],
};

// -------- Portuguese --------
const PORTUGUESE: LanguageDef = {
  id: "portuguese",
  label: "portuguese",
  morse: {
    ...LATIN_CORE,
    ...DIGITS,
    ...LATIN_PUNCT,
    Á: ".--.-",
    Â: ".-.-",
    Ã: ".--.-",
    À: ".--.-",
    Ç: "-.-..",
    É: "..-..",
    Ê: "-..-.",
    Í: "..",
    Ó: "---.",
    Ô: "---.",
    Õ: "---.",
    Ú: "..--",
  },
  letters: "abcdefghijklmnopqrstuvwxyzçãéí".split(""),
  words: [
    "o",
    "a",
    "de",
    "e",
    "do",
    "da",
    "em",
    "um",
    "para",
    "com",
    "não",
    "uma",
    "os",
    "no",
    "se",
    "na",
    "por",
    "mais",
    "as",
    "dos",
    "como",
    "mas",
    "foi",
    "ao",
    "ele",
    "das",
    "tem",
    "seu",
    "sua",
    "ou",
    "ser",
    "quando",
    "muito",
    "há",
    "nos",
    "já",
    "está",
    "eu",
    "também",
    "só",
    "pelo",
    "pela",
    "até",
    "isso",
    "ela",
    "entre",
    "era",
    "depois",
    "sem",
    "mesmo",
    "aos",
    "ter",
    "seus",
    "quem",
    "nas",
    "me",
    "esse",
    "eles",
    "você",
    "essa",
  ],
  sentences: [
    "a rápida raposa marrom salta sobre o cão preguiçoso",
    "água mole em pedra dura tanto bate até que fura",
    "quem não arrisca não petisca",
  ],
  twisters: [
    "o rato roeu a roupa do rei de roma",
    "três pratos de trigo para três tigres tristes",
    "atrás da porta torta tem uma pata morta",
  ],
};

// -------- Italian --------
const ITALIAN: LanguageDef = {
  id: "italian",
  label: "italian",
  morse: {
    ...LATIN_CORE,
    ...DIGITS,
    ...LATIN_PUNCT,
    À: ".--.-",
    È: ".-..-",
    É: "..-..",
    Ì: "..",
    Ò: "---.",
    Ù: "..--",
  },
  letters: "abcdefghijklmnopqrstuvwxyzàèéìòù".split(""),
  words: [
    "il",
    "di",
    "che",
    "e",
    "la",
    "a",
    "un",
    "in",
    "per",
    "è",
    "una",
    "sono",
    "con",
    "non",
    "si",
    "da",
    "ma",
    "ha",
    "le",
    "mi",
    "ci",
    "se",
    "ti",
    "io",
    "come",
    "più",
    "lo",
    "cosa",
    "tutto",
    "anche",
    "quando",
    "ora",
    "molto",
    "essere",
    "fare",
    "dire",
    "bene",
    "così",
    "te",
    "perché",
    "altro",
    "poi",
    "dove",
    "tu",
    "loro",
    "lui",
    "lei",
    "stesso",
    "ogni",
    "mai",
    "sempre",
    "ancora",
    "casa",
    "tempo",
    "mondo",
    "vita",
  ],
  sentences: [
    "ma la volpe col suo balzo ha raggiunto il quieto fido",
    "chi dorme non piglia pesci",
    "meglio tardi che mai",
    "l unione fa la forza",
  ],
  twisters: [
    "trentatré trentini entrarono a trento tutti e trentatré trotterellando",
    "sopra la panca la capra campa sotto la panca la capra crepa",
    "apelle figlio di apollo fece una palla di pelle di pollo",
  ],
};

// -------- Russian (Cyrillic Morse) --------
const RUSSIAN: LanguageDef = {
  id: "russian",
  label: "russian",
  morse: {
    А: ".-",
    Б: "-...",
    В: ".--",
    Г: "--.",
    Д: "-..",
    Е: ".",
    Ж: "...-",
    З: "--..",
    И: "..",
    Й: ".---",
    К: "-.-",
    Л: ".-..",
    М: "--",
    Н: "-.",
    О: "---",
    П: ".--.",
    Р: ".-.",
    С: "...",
    Т: "-",
    У: "..-",
    Ф: "..-.",
    Х: "....",
    Ц: "-.-.",
    Ч: "---.",
    Ш: "----",
    Щ: "--.-",
    Ъ: "--.--",
    Ы: "-.--",
    Ь: "-..-",
    Э: "..-..",
    Ю: "..--",
    Я: ".-.-",
    ...DIGITS,
    ".": "......",
    ",": ".-.-.-",
    "?": "..--..",
    "!": "--..--",
    ":": "---...",
    ";": "-.-.-.",
    "(": "-.--.-",
    ")": "-.--.-",
    "-": "-....-",
    "/": "-..-.",
    '"': ".-..-.",
    "'": ".----.",
  },
  letters: "абвгдежзийклмнопрстуфхцчшщъыьэюя".split(""),
  words: [
    "и",
    "в",
    "не",
    "на",
    "я",
    "быть",
    "он",
    "с",
    "что",
    "а",
    "по",
    "это",
    "она",
    "этот",
    "к",
    "но",
    "они",
    "мы",
    "как",
    "из",
    "у",
    "который",
    "то",
    "за",
    "свой",
    "что",
    "весь",
    "год",
    "от",
    "так",
    "о",
    "для",
    "ты",
    "же",
    "все",
    "тот",
    "мочь",
    "вы",
    "человек",
    "такой",
    "его",
    "сказать",
    "только",
    "или",
    "ещё",
    "бы",
    "себя",
    "один",
    "как",
    "уже",
    "до",
    "время",
    "если",
    "сам",
    "когда",
    "другой",
    "вот",
    "говорить",
    "наш",
    "мой",
  ],
  sentences: [
    "съешь же ещё этих мягких французских булок да выпей чаю",
    "терпение и труд всё перетрут",
    "век живи век учись",
  ],
  twisters: [
    "карл у клары украл кораллы а клара у карла украла кларнет",
    "на дворе трава на траве дрова",
    "шла саша по шоссе и сосала сушку",
  ],
};

// -------- Ukrainian (Cyrillic Morse, Ukrainian set) --------
const UKRAINIAN: LanguageDef = {
  id: "ukrainian",
  label: "ukrainian",
  morse: {
    А: ".-",
    Б: "-...",
    В: ".--",
    Г: "--.",
    Ґ: "--.-.",
    Д: "-..",
    Е: ".",
    Є: "..-..",
    Ж: "...-",
    З: "--..",
    И: "-.--",
    І: "..",
    Ї: ".---.",
    Й: ".---",
    К: "-.-",
    Л: ".-..",
    М: "--",
    Н: "-.",
    О: "---",
    П: ".--.",
    Р: ".-.",
    С: "...",
    Т: "-",
    У: "..-",
    Ф: "..-.",
    Х: "....",
    Ц: "-.-.",
    Ч: "---.",
    Ш: "----",
    Щ: "--.-",
    Ь: "-..-",
    Ю: "..--",
    Я: ".-.-",
    ...DIGITS,
    ".": "......",
    ",": ".-.-.-",
    "?": "..--..",
  },
  letters: "абвгґдеєжзиіїйклмнопрстуфхцчшщьюя".split(""),
  words: [
    "і",
    "в",
    "не",
    "на",
    "я",
    "що",
    "це",
    "він",
    "вона",
    "ми",
    "ви",
    "вони",
    "до",
    "за",
    "по",
    "з",
    "о",
    "у",
    "як",
    "але",
    "або",
    "так",
    "ні",
    "там",
    "тут",
    "коли",
    "де",
    "хто",
    "чому",
    "тільки",
    "ще",
    "вже",
    "дуже",
    "добре",
    "день",
    "ніч",
    "ранок",
    "вечір",
    "рік",
    "час",
    "рука",
    "око",
    "серце",
    "земля",
    "небо",
    "вода",
  ],
  sentences: ["щука у ставку плавала тихо", "хто рано встає тому бог дає"],
};

// -------- Greek --------
const GREEK: LanguageDef = {
  id: "greek",
  label: "greek",
  morse: {
    Α: ".-",
    Β: "-...",
    Γ: "--.",
    Δ: "-..",
    Ε: ".",
    Ζ: "--..",
    Η: "....",
    Θ: "-.-.",
    Ι: "..",
    Κ: "-.-",
    Λ: ".-..",
    Μ: "--",
    Ν: "-.",
    Ξ: "-..-",
    Ο: "---",
    Π: ".--.",
    Ρ: ".-.",
    Σ: "...",
    Τ: "-",
    Υ: "-.--",
    Φ: "..-.",
    Χ: "----",
    Ψ: "--.-",
    Ω: ".--",
    ...DIGITS,
    ".": ".-.-.-",
    ",": "--..--",
    "?": "..--..",
    "!": "-.-.--",
  },
  letters: "αβγδεζηθικλμνξοπρστυφχψω".split(""),
  words: [
    "και",
    "να",
    "το",
    "τη",
    "της",
    "τον",
    "την",
    "του",
    "των",
    "στο",
    "στη",
    "για",
    "από",
    "με",
    "σε",
    "είναι",
    "δεν",
    "θα",
    "ότι",
    "όταν",
    "όπως",
    "αλλά",
    "αν",
    "κάτι",
    "κάποιος",
    "εδώ",
    "εκεί",
    "τώρα",
    "πάντα",
    "ποτέ",
    "ένα",
    "μία",
    "δύο",
    "τρία",
    "άνθρωπος",
    "μέρα",
    "νύχτα",
    "χρόνος",
    "κόσμος",
    "ζωή",
    "χέρι",
    "μάτι",
  ],
  sentences: ["ξεσκεπάζω την ψυχοφθόρα βδελυγμία", "η αρχή είναι το ήμισυ του παντός"],
};

// -------- Hebrew --------
const HEBREW: LanguageDef = {
  id: "hebrew",
  label: "hebrew",
  rtl: true,
  morse: {
    א: ".-",
    ב: "-...",
    ג: "--.",
    ד: "-..",
    ה: "---",
    ו: ".",
    ז: "--..",
    ח: "....",
    ט: "..-",
    י: "..",
    כ: "-.-",
    ל: ".-..",
    מ: "--",
    נ: "-.",
    ס: "-.-.",
    ע: ".---",
    פ: ".--.",
    צ: ".--",
    ק: "--.-",
    ר: ".-.",
    ש: "...",
    ת: "-",
    ...DIGITS,
    ".": ".-.-.-",
    ",": "--..--",
    "?": "..--..",
  },
  letters: "אבגדהוזחטיכלמנסעפצקרשת".split(""),
  words: [
    "של",
    "את",
    "על",
    "עם",
    "אני",
    "הוא",
    "היא",
    "אנחנו",
    "אתם",
    "הם",
    "לא",
    "כן",
    "מה",
    "איך",
    "למה",
    "כי",
    "אבל",
    "או",
    "גם",
    "רק",
    "עוד",
    "כבר",
    "שם",
    "פה",
    "עכשיו",
    "תמיד",
    "אף",
    "יש",
    "אין",
    "היה",
    "יום",
    "לילה",
    "שנה",
    "זמן",
    "איש",
    "אישה",
    "ילד",
    "בית",
    "עיר",
    "ארץ",
    "שמיים",
    "ים",
    "מים",
    "אור",
  ],
  sentences: ["דג סקרן שט בים מאוכזב ולפתע מצא חברה", "סוף מעשה במחשבה תחילה"],
};

// -------- Arabic --------
const ARABIC: LanguageDef = {
  id: "arabic",
  label: "arabic",
  rtl: true,
  morse: {
    ا: ".-",
    ب: "-...",
    ت: "-",
    ث: "-.-.",
    ج: ".---",
    ح: "....",
    خ: "---",
    د: "-..",
    ذ: "--..",
    ر: ".-.",
    ز: "---.",
    س: "...",
    ش: "----",
    ص: "-..-",
    ض: "...-",
    ط: "..-",
    ظ: "-...-",
    ع: ".-.-",
    غ: "--.",
    ف: "..-.",
    ق: "--.-",
    ك: "-.-",
    ل: ".-..",
    م: "--",
    ن: "-.",
    ه: "..-..",
    و: ".--",
    ي: "..",
    ء: ".",
    ...DIGITS,
    ".": ".-.-.-",
    ",": "--..--",
    "?": "..--..",
  },
  letters: "ابتثجحخدذرزسشصضطظعغفقكلمنهوي".split(""),
  words: [
    "في",
    "من",
    "على",
    "إلى",
    "عن",
    "مع",
    "هذا",
    "هذه",
    "ذلك",
    "التي",
    "الذي",
    "كان",
    "لقد",
    "قد",
    "لا",
    "نعم",
    "أنا",
    "أنت",
    "هو",
    "هي",
    "نحن",
    "هم",
    "ما",
    "كيف",
    "لماذا",
    "أين",
    "متى",
    "كل",
    "بعض",
    "قبل",
    "بعد",
    "أول",
    "يوم",
    "ليل",
    "شمس",
    "قمر",
    "بيت",
    "ماء",
    "نار",
    "أرض",
    "سماء",
    "رجل",
    "امرأة",
    "ولد",
    "بنت",
    "كتاب",
  ],
  sentences: [
    "نص حكيم له سر قاطع وذو شأن عظيم مكتوب على ثوب أخضر ومغلف بجلد أزرق",
    "العلم نور والجهل ظلام",
  ],
};

// -------- Persian (Farsi) --------
const PERSIAN: LanguageDef = {
  id: "persian",
  label: "persian",
  rtl: true,
  morse: {
    ا: ".-",
    ب: "-...",
    پ: ".--.",
    ت: "-",
    ث: "-.-.",
    ج: ".---",
    چ: "---.",
    ح: "....",
    خ: "-..-",
    د: "-..",
    ذ: "--..",
    ر: ".-.",
    ز: "---..",
    ژ: "--.",
    س: "...",
    ش: "----",
    ص: "-..-..",
    ض: "..-..",
    ط: "..-",
    ظ: "-...-",
    ع: ".-.-",
    غ: "..-.-",
    ف: "..-.",
    ق: "---.",
    ک: "-.-",
    گ: "--.-",
    ل: ".-..",
    م: "--",
    ن: "-.",
    و: ".--",
    ه: "...-.",
    ی: "..",
    ...DIGITS,
    ".": ".-.-.-",
    ",": "--..--",
    "?": "..--..",
  },
  letters: "ابپتثجچحخددرزژسشصضطظعغفقکگلمنوهی".split(""),
  words: [
    "و",
    "در",
    "به",
    "از",
    "که",
    "این",
    "با",
    "را",
    "است",
    "می",
    "شد",
    "نه",
    "بر",
    "تا",
    "یک",
    "دو",
    "هم",
    "اما",
    "اگر",
    "هر",
    "چه",
    "کی",
    "کجا",
    "چرا",
    "چگونه",
    "کسی",
    "چیزی",
    "همه",
    "هیچ",
    "بعد",
    "قبل",
    "امروز",
    "دیروز",
    "روز",
    "شب",
    "سال",
    "ماه",
    "انسان",
    "مرد",
    "زن",
    "کودک",
    "خانه",
    "شهر",
    "کشور",
    "آسمان",
    "زمین",
    "آب",
  ],
  sentences: ["هر که بامش بیش برفش بیشتر", "آب در کوزه و ما تشنه لبان می گردیم"],
};

// -------- Japanese (Wabun Code, katakana) --------
const JAPANESE: LanguageDef = {
  id: "japanese",
  label: "japanese",
  morse: {
    イ: ".-",
    ロ: ".-.-",
    ハ: "-...",
    ニ: "-.-.",
    ホ: "-..",
    ヘ: ".",
    ト: "..-..",
    チ: "..-.",
    リ: "--.",
    ヌ: "....",
    ル: "-.--.",
    ヲ: ".---",
    ワ: "-.-",
    カ: ".-..",
    ヨ: "--",
    タ: "-.",
    レ: "---",
    ソ: "---.",
    ツ: ".--.",
    ネ: "--.-",
    ナ: ".-.",
    ラ: "...",
    ム: "-",
    ウ: "..-",
    ヰ: ".-..-",
    ノ: "..--",
    オ: ".-...",
    ク: "...-",
    ヤ: ".--",
    マ: "-..-",
    ケ: "-.--",
    フ: "--..",
    コ: "----",
    エ: "-.---",
    テ: ".-.--",
    ア: "--.--",
    サ: "-.-.-",
    キ: "-.-..",
    ユ: "-..--",
    メ: "-...-",
    ミ: "..-.-",
    シ: "--.-.",
    ヱ: ".--..",
    ヒ: "--..-",
    モ: "-..-.",
    セ: ".---.",
    ス: "---.-",
    ン: ".-.-.",
    "゛": "..",
    "゜": "..--.",
    ー: ".--.-",
    "、": ".-.-.-",
    ...DIGITS,
  },
  letters:
    "イロハニホヘトチリヌルヲワカヨタレソツネナラムウヰノオクヤマケフコエテアサキユメミシヱヒモセスン".split(
      "",
    ),
  words: [
    "ワタシ",
    "アナタ",
    "カレ",
    "カノジョ",
    "ココ",
    "ソコ",
    "アソコ",
    "コレ",
    "ソレ",
    "アレ",
    "ナニ",
    "ダレ",
    "イツ",
    "ドコ",
    "ナゼ",
    "ドウ",
    "ハイ",
    "イイエ",
    "アリガトウ",
    "スミマセン",
    "コンニチハ",
    "サヨウナラ",
    "ヒト",
    "モノ",
    "トキ",
    "ヒ",
    "ツキ",
    "ホシ",
    "ソラ",
    "ウミ",
    "ヤマ",
    "カワ",
    "ハナ",
    "キ",
    "ミズ",
    "ヒカリ",
    "ホン",
    "ガッコウ",
    "セイト",
    "センセイ",
    "トモダチ",
    "カゾク",
    "ニホン",
    "コトバ",
    "オンガク",
    "エイガ",
  ],
  sentences: [
    "イロハニホヘト チリヌルヲ ワカヨタレソ ツネナラム",
    "ウヰノオクヤマ ケフコエテ アサキユメミシ ヱヒモセス",
  ],
};

// -------- Thai --------
const THAI: LanguageDef = {
  id: "thai",
  label: "thai",
  morse: {
    ก: "--.",
    ข: "-.-.",
    ค: "-.-",
    ง: "-.--.",
    จ: "-..-.",
    ฉ: "----",
    ช: "-..-",
    ซ: "--..",
    ญ: ".---",
    ด: "-..",
    ต: "-",
    ถ: "-.-..",
    ท: "-..--",
    น: "-.",
    บ: "-...",
    ป: ".--.",
    ผ: "--.-",
    ฝ: "-.-.-",
    พ: ".--..",
    ฟ: "..-.",
    ม: "--",
    ย: "-.--",
    ร: ".-.",
    ล: ".-..",
    ว: ".--",
    ส: "...",
    ห: "....",
    อ: "-...-",
    ฮ: "--.--",
    ะ: ".-...",
    า: ".-",
    "ิ": "..-..",
    "ี": "..",
    "ึ": "..--.",
    "ื": "..--",
    "ุ": "..-.-",
    "ู": "---.",
    เ: ".",
    แ: ".-.-",
    ไ: ".-..-",
    โ: "---",
    ำ: "...-.",
    "่": "..-",
    "้": "...-",
    "๊": "--...",
    "๋": "-..-..",
    ...DIGITS,
  },
  letters: "กขคงจฉชซญดตถทนบปผฝพฟมยรลวสหอฮ".split(""),
  words: [
    "ผม",
    "ฉัน",
    "คุณ",
    "เขา",
    "เธอ",
    "เรา",
    "พวกเขา",
    "นี่",
    "นั่น",
    "อะไร",
    "ใคร",
    "ที่ไหน",
    "เมื่อไหร่",
    "ทำไม",
    "อย่างไร",
    "ใช่",
    "ไม่",
    "ขอบคุณ",
    "ขอโทษ",
    "สวัสดี",
    "ลาก่อน",
    "คน",
    "วัน",
    "คืน",
    "ปี",
    "เดือน",
    "บ้าน",
    "เมือง",
    "ประเทศ",
    "ภาษา",
    "หนังสือ",
    "น้ำ",
    "ไฟ",
    "ดิน",
    "ฟ้า",
    "ดาว",
    "พระอาทิตย์",
    "พระจันทร์",
  ],
  sentences: ["ช้างเผือกอยู่ในป่าใหญ่", "ความพยายามอยู่ที่ไหน ความสำเร็จอยู่ที่นั่น"],
};

// -------- Hindi / Devanagari --------
const HINDI: LanguageDef = {
  id: "hindi",
  label: "hindi",
  morse: {
    अ: ".-",
    आ: ".-.-",
    इ: "..",
    ई: "..-..",
    उ: "..-",
    ऊ: "---.",
    ऋ: ".-.-.",
    ए: "...-.",
    ऐ: ".-..",
    ओ: "---",
    औ: "...-",
    क: "-.-",
    ख: "-..-",
    ग: "--.",
    घ: "---.",
    च: "-.-.",
    छ: "----",
    ज: ".---",
    झ: "..-.",
    ट: "-",
    ठ: "...-.",
    ड: "..-..",
    ढ: "...-",
    ण: "..--",
    त: "-..",
    थ: "-...",
    द: "..",
    ध: ".-..",
    न: "-.",
    प: ".--.",
    फ: "..-.",
    ब: "-...",
    भ: "-.-..",
    म: "--",
    य: "-.--",
    र: ".-.",
    ल: ".-..",
    व: ".--",
    श: "--..",
    ष: "-..-",
    स: "...",
    ह: "....",
    "ं": ".-.-.",
    "ः": "..-.",
    ...DIGITS,
  },
  letters: "अआइईउऊएऐओऔकखगघचछजझटठडढणतथदधनपफबभमयरलवशषसह".split(""),
  words: [
    "मैं",
    "तुम",
    "आप",
    "वह",
    "हम",
    "वे",
    "यह",
    "ये",
    "कौन",
    "क्या",
    "कहाँ",
    "कब",
    "क्यों",
    "कैसे",
    "हाँ",
    "नहीं",
    "धन्यवाद",
    "नमस्ते",
    "अलविदा",
    "दिन",
    "रात",
    "साल",
    "माह",
    "घर",
    "शहर",
    "देश",
    "भाषा",
    "किताब",
    "पानी",
    "आग",
    "धरती",
    "आकाश",
    "सूरज",
    "चाँद",
    "तारा",
    "फूल",
    "पेड़",
    "नदी",
    "पहाड़",
    "समुद्र",
    "रास्ता",
  ],
  sentences: ["जहाँ चाह वहाँ राह", "अब पछताए होत क्या जब चिड़िया चुग गई खेत"],
};

export const LANGUAGES: LanguageDef[] = [
  ENGLISH,
  SPANISH,
  FRENCH,
  GERMAN,
  PORTUGUESE,
  ITALIAN,
  RUSSIAN,
  UKRAINIAN,
  GREEK,
  HEBREW,
  ARABIC,
  PERSIAN,
  JAPANESE,
  THAI,
  HINDI,
];

const LANG_BY_ID = new Map(LANGUAGES.map((l) => [l.id, l]));

export function getLanguage(id: string): LanguageDef {
  return LANG_BY_ID.get(id) ?? ENGLISH;
}
